image: asegroup11/all_servers:citynet

before_script:
  - python -V                                   # Print out python version for debugging
  - pip3 install flake8  # you can also use tox

stages:
  - compile
  - test

build_backend:
  stage: compile
  script:
    - cd backend
    - flake8 .

test:
  stage: test
  script:
  - all_test.sh
