image: asegroup11/all_servers:citynet

before_script:
  - python -V  # Print out python version for debugging

stages:
  - syntax

backend_syntax:
  stage: syntax
  script:
    - cd backend
    - flake8 .
    - bash all_test.sh from_docker
