image: asegroup11/all_servers:citynet

before_script:
  - python -V                                   # Print out python version for debugging
  - pip3 install flake8  # you can also use tox

stages:
  - build
  - test

build_backend:
  stage: build
  script:
    - cd backend
    - flake8 .
    - python setup.py install

test:
  stage: test
  script:
  - cd backend
  - python setup.py test
