image: asegroup11/all_servers:citynet

before_script:
  - python -V  # Print out python version for debugging

stages:
  - syntax

syntax_tests:
  stage: syntax
  script:
    - flake8 cityback
    - bash all_test.sh from_docker
