image: asegroup11/all_servers:citynet

before_script:
  - python -V                                   # Print out python version for debugging

test:
  script:
  - python test/test.py
  - pip3 install flake8  # you can also use tox
  - flake8 .
install:
  # Install unittest2pytest
  - pip install -e .

  # Install dependencies for tests.
  - pip install -r tests/requirements_tests.txt | cat

script:
  - py.test -vv