# Generated by Django 2.0.2 on 2018-03-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdemo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocketClient',
        ),
    ]
