# Generated by Django 2.0.2 on 2018-03-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0007_add_sql_floor_function'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBikesStationAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, null=True)),
                ('avg_available_bikes', models.IntegerField()),
                ('parent_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.DublinBikesStation')),
            ],
        ),
    ]
