# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DublinBikesStation',
            fields=[
                ('station_number', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=120)),
                ('bonus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DublinBikesStationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('parent_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.DublinBikesStation')),
            ],
        ),
    ]
