# Generated by Django 2.0.2 on 2018-03-06 14:36
import datetime

from django.db import migrations, models


def migrate_str_to_datetime(apps, schema_editor):

    MyModel = apps.get_model('storage', 'dublinbikesstationrealtimeupdate')

    for mm in MyModel.objects.all():

        field_old_time = mm.lu_old
        field_new_int = datetime.datetime.utcfromtimestamp(
            int(field_old_time)/1000).replace(
            tzinfo=datetime.timezone.utc)
        mm.last_update = field_new_int
        mm.save()


class Migration(migrations.Migration):
    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dublinbikesstationrealtimeupdate',
            old_name='last_update',
            new_name='lu_old',
        ),
        migrations.AddField(
            model_name='dublinbikesstationrealtimeupdate',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(migrate_str_to_datetime),
        migrations.RemoveField(
            model_name='dublinbikesstationrealtimeupdate',
            name='lu_old',
        )
    ]