# Generated by Django 2.0.2 on 2018-03-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20180313_1937'),
    ]

    operations = [
        migrations.RunSQL(
            """
        CREATE FUNCTION date_round(base_date timestamptz, round_interval INTERVAL)
        RETURNS timestamptz AS $BODY$ SELECT TO_TIMESTAMP((EXTRACT(epoch FROM $1)::INTEGER
        + EXTRACT(epoch FROM $2)::INTEGER / 2) / EXTRACT(epoch FROM $2)::INTEGER *
        EXTRACT(epoch FROM $2)::INTEGER) $BODY$ LANGUAGE SQL STABLE;
        """
        )
    ]
