# Generated by Django 2.0.2 on 2018-03-15 18:04

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


def migrate_float_to_point(apps, schema_editor):

    MyModel = apps.get_model('data_storage', 'dublinbikesstation')

    for mm in MyModel.objects.all():

        point = Point(
            mm.longitude, mm.latitude,
            srid=4326  # WGS 84
        )
        mm.position = point
        mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0003_add_sql_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublinbikesstation',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(
                null=True, srid=4326),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_float_to_point),
        migrations.AlterField(
            model_name='dublinbikesstation',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(
                null=False, srid=4326),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dublinbikesstation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dublinbikesstation',
            name='longitude',
        ),
    ]
