# Generated by Django 2.0.2 on 2018-03-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_bike_updates_every_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublinbikesstationrealtimeupdate',
            name='timestamp',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
