# Generated by Django 2.0.2 on 2018-03-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage', '0006_auto_20180321_1441'),
    ]

    operations = [
        migrations.RunSQL(
            """
        CREATE FUNCTION date_floor(base_date timestamptz, round_interval INTERVAL)
        RETURNS timestamptz AS $BODY$ SELECT TO_TIMESTAMP((EXTRACT(epoch FROM $1)::INTEGER
        ) / EXTRACT(epoch FROM $2)::INTEGER *
        EXTRACT(epoch FROM $2)::INTEGER) $BODY$ LANGUAGE SQL STABLE;
        """
        )
    ]
