# Generated by Django 2.0.2 on 2018-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_interface', '0002_auto_20180326_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dublinbikesstationaverage',
            name='avg_available_bikes',
        ),
        migrations.AddField(
            model_name='dublinbikesstationaverage',
            name='avg_occupancy',
            field=models.FloatField(null=True),
        ),
    ]
